spring:
  application:
    name: vitale
  lifecycle:
    timeout-per-shutdown-phase: 15s
  main:
    banner-mode: off
  config:
    import: "optional:configserver:"
  cloud:
    config:
      import-check:
        enabled: false
#      uri: http://localhost:8888
#      request-connect-timeout: 5000
#      request-read-timeout: 5000
#      fail-fast: false
#      retry:
#        max-attempts: 6
#        initial-interval: 1000
#        max-interval: 2000
#        multiplier: 1.1
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

  flyway:
    baseline-on-migrate: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh

server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
  shutdown: graceful

#polar:
#  greeting: Welcome to the local book catalog!
